version: '3.8'

services:
  node:
    build: ./node
    ports:
      - 3000:3000
    networks:
      - node-network

  nginx:
    build: ./nginx
    ports:
      - 80:80
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
